baseurl = "https://lukeindykiewicz.github.com/"
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Luke Indykiewicz"
title = "luekindykiewicz"
pygmentsuseclasses = true
# disqusShortname = "cocoaexamplesite" # TODO: optional, comment out to disable Disqus
pluralizelisttitles = false

[permalinks]
fixed = ":title/"
blog = "blog/:slug/"

[params]
Author = "Luke Indykiewicz"
CacheBuster = true
DateForm = "2 Jan 2006"
DateFormFull = "Mon, 2 Jan 2006, 15:04:05 MST"
Description = "Blog"
Email = "you@example.space" # TODO:
FaviconFile = "img/favico.ico"
GATracker = "UA-73272302-1"
GitHub = "//github.com/lukeindykiewicz"
Initials = "li" # displayed on single post page; DEPRECATED in v0.3.0
Lang = "en"
LinkedIn = "//linkedin.com/in/lukaszindykiewicz"
Twitter = "//twitter.com/lukeindykiewicz"
ExtraCssFiles = [ "/css/override.css" ] # relative to public directory
